version: '3.8'
services:
  server:
    deploy:
          resources:
            reservations:
              devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: server
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow
      - PORT=42013